name = "ObjectDiff"
uuid = "65a5682a-8867-4307-8e2e-e8b07d326546"
authors = ["theogf <theo.galyfajou@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractTrees = "0.4"
Test = "1"
julia = "1.10"
